### ISSUE TITLE
Comma format number

### ISSUE THREAD

**Issue by lmrarturo** [nkoik/vue-animated-number#1]
I need to put a comma in the number, is that posible?

Maybe in the format put something like `return number.toFixed(-3);`

Thanks!

**Comment by nkoik** [comment]
It's not an issue.
number.toFixed() is a JS method and gets non-negative numbers

**Comment by n1ckbren** [comment]
```
    formatNumber(number){
      let nf = new Intl.NumberFormat("en-US"); // commas, US format
      return nf.format(number.toFixed(0)); // hide fractions
    }
```
