### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by lathanbritz** [nkoik/vue-animated-number#14]
even if speccing formatting to use more decimals. It still rounds to the 6'th decimal place.

eg. try showing 
0.0000181234

it gets truncated to
0.0000180000

```
theFormat(number) {
   return number.toFixed(10);
},
```

**Comment by titusdecali** [comment]
You can see below that when you extend the decimal it is some kind of rounding error.
Playing around with the [codesandbox](https://codesandbox.io/s/8256nwlq78), I can make it happen now but it is a bit random and intermittent.

![rounding error](https://user-images.githubusercontent.com/4532534/139620490-65da6384-f58d-4459-92b6-bfdb374acf72.gif)

**Comment by titusdecali** [comment]
@nkoik I thank you for building this package, however you should provide at least a minimal amount of interaction with your users. I've sent you an email and left very clear notes above, yet after 20 days there is no response. Without updates, it wastes people's time to rip out code and replace it with something that is better supported, and during the in-between time we are wondering if updates will ever be done at all.

**Comment by lathanbritz** [comment]
others looking for a solution it seems to be fixed and working for me here https://github.com/solancer/vue-animated-number
