### ISSUE TITLE
Doesnt work with NuxtJS

### ISSUE THREAD

**Issue by limsocheat** [nkoik/vue-animated-number#3]
I installed it with VueCLI3, it is working very well indeed, but when I move to NuxtJS, the package cause the whole project error: 

```
SyntaxError
Unexpected identifier
```

![image](https://user-images.githubusercontent.com/6656644/62021251-81d50700-b1f0-11e9-9e7e-e543edb8c956.png)

**In plugins/number-animation.js**

```
import Vue from 'vue'
import VueNumber from 'vue-number-animation'

Vue.use(VueNumber)
```

**In nuxt.config.js**

```
plugins: [
    'plugins/vue-masonry-css',
    'plugins/number-animation'
  ],
```

**Comment by tomhatzer** [comment]
@limsocheat did you try loading the plugin as client-side only plugin?

eg.
```
plugins: [
    'plugins/vue-masonry-css',
    {src: 'plugins/number-animation', ssr: false}
  ],
```

**Comment by spocock** [comment]
Confirmed that loading as a client-side plugin works with nuxtjs.

`
plugins: [
    {src: 'plugins/number-animation', ssr: false}
  ],
`

**Comment by jetlej** [comment]
Yes, but if you do ssr: false, then you get this error: 

`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

**Comment by drohss** [comment]
@jetlej wrapping the <number> tag inside <client-only> seems to resolve this warning
Can read more about <client-only> here: https://nuxtjs.org/docs/2.x/features/nuxt-components/

**Comment by migo315** [comment]
I'm using it with NuxtJS without any error (see https://coaster.cloud/en)

**Comment by IgnisDa** [comment]
To avoid errors, you will have to use it like so:

```vue
   <client-only>
      <number
        :from="0"
        :to="2569"
        :duration="5"
        :delay="1"
        easing="Power1.easeOut"
      ></number>
    </client-only>
```

See https://nuxtjs.org/docs/2.x/features/nuxt-components#the-client-only-component.
