### ISSUE TITLE
Allow prop to display number with localeString

### ISSUE THREAD

**Issue by JoeSziver** [nkoik/vue-animated-number#6]
Normally you can add .toLocaleString('en') to display the number with commas inside.

Ex:

1000 => 1,000

I am currently using a workaround by modifying the source Number.vue to display:

parseFloat(tweenedNumber).toLocaleString('en',{ minimumFractionDigits: 2 })

**Comment by ronaldohoch** [comment]
You can use this.
![image](https://user-images.githubusercontent.com/2287371/71682582-e3386d80-2d6e-11ea-8f84-4288ee02a851.png)

`
theFormat(number) {
      return number.toLocaleString('en',{ minimumFractionDigits: 2 });
},
`
![image](https://user-images.githubusercontent.com/2287371/71682731-46c29b00-2d6f-11ea-95c9-91d564b9cc35.png)

**Comment by JoeSziver** [comment]
Completely slipped my mind. Thanks
