### ISSUE TITLE
play is not a function

### ISSUE THREAD

**Issue by AhmedNegm95** [nkoik/vue-animated-number#7]
plz i have an error when calling this.$refs.count0.play(); 
i get an error saying "TypeError: this.$refs.count0.play is not a function"

![Capture](https://user-images.githubusercontent.com/50294058/75112644-6038e280-564e-11ea-916b-04e3f5b93a99.PNG)

**Comment by nkoik** [comment]
Check your refs

> plz i have an error when calling this.$refs.count0.play();
> i get an error saying "TypeError: this.$refs.count0.play is not a function"
> 
> ![Capture](https://user-images.githubusercontent.com/50294058/75112644-6038e280-564e-11ea-916b-04e3f5b93a99.PNG)

Check your refs
