### ISSUE TITLE
Cannot update gsap to a non-vulnerable version

### ISSUE THREAD

**Issue by solancer** [nkoik/vue-animated-number#8]
Dependabot cannot update gsap to a non-vulnerable version

The latest possible version that can be installed is 2.1.3 because of the following conflicting dependency:

vue-number-animation@1.0.5 requires gsap@^2.0.1
The earliest fixed version is 3.6.0.

![Screenshot 2021-01-28 at 5 03 02 pm](https://user-images.githubusercontent.com/800668/106133006-b087c100-618a-11eb-84db-ca45425419a2.png)

**Comment by Ragash** [comment]
Same

**Comment by migo315** [comment]
Same here

**Comment by jsandfordhughes** [comment]
Can you confirm when you will bump 1.0.6 on npm?

**Comment by shsaleh** [comment]
update npm pls

**Comment by jsandfordhughes** [comment]
@nkoik @jdefelice please can you update NPM?

**Comment by Darmord7** [comment]
Fix here: https://security.snyk.io/package/npm/gsap/2.1.3 :)
